### ISSUE TITLE
Files cannot (quite) be arranged into separate Assemblies in Unity 2017.

### ISSUE THREAD

**Issue by WazWaz** [umasteeringgroup/UMA#116]
The Assembly Definition Files feature of Unity 2017 is very useful for users of sourcecode-distributed libraries such as UMA.

When setting up asmdefs for UMA, I found that the partial class RaceInspector is spread across multiple directories:

1. UMA\Core\StandardAssets\Extensions\DynamicCharacterSystem\Scripts\Editor
2. UMA\Core\StandardAssets\UMA\Scripts\Editor

This doesn't work - partial classes need to be in the one assembly, so I moved the former into a DCS subdirectory of the latter so they could be in one assembly.

Also, I found that many asmdefs are required, as Editor and non-Editor code must go in separate DLLs, yet UMA has numerous Editor script directories within other Script directories. While this is not a problem, and indeed improves build time if modifying UMA, having each user make their own asmdefs is not good, and getting the dependencies right is a little tricky. I ended up with 8 assemblies: a top-level UMA assembly (which would need to be shipped with game releases) and one for each Editor directory and for UMA Examples (which would not need to be shipped in final builds). This appears to be the minimal number with the current structure.

**Comment by kenamis** [comment]
Hey, thanks for reminding me about this.  I'll try to work on this in the next couple weeks/month.  Everyone seems busy lately, but I didn't want you to think this has gone unnoticed.

**Comment by kenamis** [comment]
@WazWaz 
This is what I came up with.  Do you want to try it or have any comments on this set up?  If it looks good I'll post it on the wiki.  We're not sure about including it with uma2 because we've already created branches for uma3, but it'll get added for uma3.

Setting up UMA with Assembly Definition Files
https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html

1)	First, we’ll need to restructure the folders and scripts somewhat.
2)	Move “DNA” folder from “UMA/Content/UMA_Core/HumanShared” to under “UMA/Core”
3)	Create an “Editor” folder under “UMA/Core” and “UMA/Examples”.
4)	Now, move all the scripts in each of the existing Editor folders to their respective new Editor folder you just created.  You can mirror the folder layout if you wish.
5)	Under “UMA/Content”, “UMA/Core”, “UMA/Core/Editor”, UMA/Examples”, and “UMA/Examples/Editor” create an assembly definition file.  I named them;
UMA_Core
UMA_Core_Editor
UMA_Examples
UMA_Examples_Editor
UMA_Content

![image](https://user-images.githubusercontent.com/3794587/37878796-514f3524-3023-11e8-88d1-407c77ca032c.png)

**Comment by WazWaz** [comment]
Looks good as the setup for UMA3. For UMA2, keeping the files in-place as I did is adequate and makes updating easier.

Good to know this will come to users. It makes a huge difference to compile times.

**Comment by kenamis** [comment]
assembly definition files are included by default now in 2.8.1 RC
https://github.com/umasteeringgroup/UMA/releases/tag/v2.8%2C1rc1
