### ISSUE TITLE
Updates within CharacterCreated and CharacterUpdated events are ignored.

### ISSUE THREAD

**Issue by WazWaz** [umasteeringgroup/UMA#15]
If an event handler connected to CharacterCreated or CharacterUpdated itself calls eg. ForceUpdate(), no update occurs. The cause is that dirty is set _after_ calling the event. Additionally, at most 2 updates are processed per frame, even with fastGeneration.

The attached patch corrects this combined problem. Sorry, the patch doesn't follow the project's tabbing conventions (I'm a bit of a VS newb), so if applied directly, it'll need a reformat run. At the very least, I hope it better explains the issue.

[UMA-issue.txt](https://github.com/umasteeringgroup/UMA/files/1046459/UMA-issue.txt)

**Comment by Jaimi** [comment]
Thanks, this has been an annoyance for some time. I'll pull it in and look at it.

**Comment by Jaimi** [comment]
I integrated the code, but it seems like FastGeneration no longer works. If I open the crowd scene, then instead of all UMA's being generated at once, they get generated once per frame (like FastGeneration is off).  Are you seeing this behavior on your system? If not, then my merge has gone wrong.

**Comment by Jaimi** [comment]
Now that I look closer at it, there are two issues:

1. The "hideWhileGenerating" no longer works on UMACrowd.
2. Generation is about 25% slower when doing FastGeneration.

It's quite possible that I've messed something up since I had to hand-merge the file. 
[Archive.zip](https://github.com/umasteeringgroup/UMA/files/1046558/Archive.zip)

Can you compare with your version. I've attached the files.

**Comment by WazWaz** [comment]
On 2/06/2017 12:57 PM, Jaimi wrote:
>
> Now that I look closer at it, there are two issues:
>
>  1. The "hideWhileGenerating" no longer works on UMACrowd.
>  2. Generation is about 25% slower when doing FastGeneration.
>
> It's quite possible that I've messed something up since I had to 
> hand-merge the file.
> Archive.zip 
> <https://github.com/umasteeringgroup/UMA/files/1046558/Archive.zip>
>
> Can you compare with your version. I've attached the files.
>

This bit isn't merged right (UMAGeneratorBuiltin.cs):

             UMAReady();
             RemoveDirty(true);
             return true;

The UMAReady() shouldn't be there - it's done in RemoveDirty() now.

The files have a few other changes that I don't have in my UMA so I 
couldn't drop in those files to test it - I'm using master, is that right?

--
Warwick

**Comment by Jaimi** [comment]
Master is the released version of UMA.  The new development is on the UMA26 branch, and that's where I'm working.
Thanks for checking that out, I'll fix that when I get back home and run all the sample scenes, etc. 

jaimi

**Comment by Joen-UnLogick** [comment]
Just a comment on the FastGeneration.

FastGeneration allows the creation of 1 uma in 1 frame. The reason more than that wasn't supported was because it gave jitters in frame rate. 

Perhaps the time is ready for giving it a time threshold instead, only problem is that that this will produce a much more uneven framerate.

**Comment by WazWaz** [comment]
I guess it depends on the application. I my case, I want to ensure all characters are created at the start of the level - it doesn't matter if this takes 0.5 seconds, since the screen is black.

**Comment by Jaimi** [comment]
Added the ability to force all UMA to be generated in develop branch. Closed.
