### ISSUE TITLE
Option so some recipes can stay as separate meshes on the model

### ISSUE THREAD

**Issue by wirelessdreamer** [umasteeringgroup/UMA#224]
mainly for cloth, and dynamic hair. Currently with UMA clothing can't be turned into cloth, or used as an obi cloth to make naturally moving clothing.

**Comment by Jaimi** [comment]
Can this not already be done by giving it a separate UMAMaterial, or selecting "Separate Renderer" on the material? Is that broken?

**Comment by wirelessdreamer** [comment]
I'll look into it, I wasn't familiar with those options.

**Comment by kenamis** [comment]
There is the ability to use unity cloth with UMA, but it has a serious
restriction (all cloth systems seem to, including obiCloth).  If the vertex
affected by cloth physics is skinned to non-uniform bones, the cloth
simulation breaks down and is not accurate.

**Comment by kenamis** [comment]
Also, to address your title "Option so some recipes can stay as separate
meshes on the model", there is already another feature branch
(feature-RendererMgmt) with that working.  There are other use causes for
separate renderers besides cloth, but that branch is updated for cloth too
instead of the current way with a new uma material with "separate renderer"
ticked.

**Comment by Jaimi** [comment]
Closed. This has been merged into the develop branch.
