### ISSUE TITLE
what is DNA short for?

### ISSUE THREAD

**Issue by yyzz990** [umasteeringgroup/UMA#288]
Could you tell me , what is DNA short for? like DCA is short for Dynamic Character Avatar

**Comment by kenamis** [comment]
Nothing related to classes in the project or Unity.
Deoxyribonucleic acid
https://en.wikipedia.org/wiki/DNA

**Comment by Jaimi** [comment]
DNA is **deoxyribonucleic acid**, a self-replicating material which is present in nearly all living organisms as the main constituent of chromosomes. It is the carrier of genetic information.

We use the term DNA to define genetic characteristics in the models, because it is similar to actual DNA.

Also - Please use the forum, or Discord channel (see the documentation) for quick questions.

**Comment by yyzz990** [comment]
very very thanks
