### ISSUE TITLE
Unused reference resources like textures not being excluded in final building app, which causes huge app size.

### ISSUE THREAD

**Issue by leegohi04517** [umasteeringgroup/UMA#401]
**Describe the bug**
Unused reference resources like textures not being excluded in final building app, which causes huge app size.

**Environment (please complete the following information):**
 - Unity Version: 2021.3.23f1
 - UMA Version: latest
 - Rendering Pipeline: built in
 - Platform Build (if not editor): iOS

**To Reproduce**
Using flutter unity plugin and an empty scene in build settings. When click build iOS , the output data folder contains almost all uma textures which not being reference by my empty scene. I can convinced that the building output contains uma huge textures, since I unpack it with UnityAssets tools.

**Expected behavior**
Building output not include unreference resources. The final app size remain small.

**Screenshots**

**Additional context**

**Comment by Marselord** [comment]
Did you find a soluion for this? The AssetIndexer from uma is the file that references all the uma textures and that same file is getting compiled into the final build.

**Comment by Jaimi** [comment]
This is by design. Everything in the global library is possible to load at runtime, and thus has to be included in the build. You can address this many ways -- cleaning up the library, converting to use addressables (which loads/unloads items as needed), etc. This is a long conversation, and has been touched on many times, it's best to take this to discord where you can see previous conversations and get more help specific to what you are doing.
