### ISSUE TITLE
Can't make shared overlay when make RaceData.

### ISSUE THREAD

**Issue by unicon7** [umasteeringgroup/UMA#54]
I am making new race.
I separated race model and made slots(torso, hand, feet, head etc).
Separated slot share 1 overlay like HumanMale example( only torsor, feet, hand, legs are shared)

1. Add torso_slot to baseRecipe.
2. Add torso_overlay to torso_slot.
3. To share torso_overlay by leg_slot, drop leg_slot to "Add Slot" in inspector of torso_slot.
4. Can't share torso_overlay by leg_slot.

I can't make share overlay like example race.
Is this issue?

**Comment by kenamis** [comment]
Hi, this is a known issue.  It should be fixed in the release-26 branch, we just haven't pushed it to the store yet.  You want to try grabbing that is see if it fixes your issue?
If you want to just overwrite the affected files, they are:
SlotData.cs
CharacterBaseEditor.cs
RecipeEditor.cs
DynamicCharacterAvatar.cs

**Comment by unicon7** [comment]
working beautifully~
thank you a lot!
